### ISSUE TITLE
[X11] glfwSetWindowPos can not move window outside of desktop bounds

### ISSUE THREAD

**Issue by rokups** [glfw/glfw#1817]
We are using GLFW windows without decorations + glfwSetWindowPos() to move them. On X11 such windows can not move outside of desktop bounds. This behavior does not manifest on other platforms. This behavior is a consequence of `xattr.override_redirect` being set to false for normal windows.

Steps to reproduce:
1. git clone --single-branch --branch docking https://github.com/ocornut/imgui.git
2. cd imgui/examples/example_sdl_opengl3
3. make
4. ./example_sdl_opengl3
5. Drag either of Dear ImGui windows ("Hello, world!" or "Dear ImGui Demo") outside of main viewport and try to move window outside of desktop bounds.

Result: Window edge will get stuck at desktop edge. Note that this also confuses Dear ImGui and mouse inputs get registered in wrong locations, this is nothing to be concerned about.
In case of multi-monitor setups please use screen at the edge of global X11 display canvas (made up terminology, hope it makes sense). I have two monitors and i can drag these windows to stick outside of smaller screen. For clarity i attached a screenshot with market green area where window _can_ stick out.
![image](https://user-images.githubusercontent.com/19151258/101619688-4705f480-3a1c-11eb-9457-5a616e271823.png)

Expected result: Dear ImGui window should be able to stick outside of desktop bounds, just like we can drag any other window by it's decorations to stick out of bounds.

Tested GLFW version: current master (7e8da57).

**Comment by tquante** [comment]
I ran into the same issue while tinkering with X11 I have fixed this behaviour by using _NET_MOVERESIZE_WINDOW as described here [](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm45841377361904)

@elmindreda  I am not familiar with the glfw constraints on using _NET_XXX atoms. I have seen some in x11_init . Would it be okay to query for support of the atom and use it for glfwSetWindowPosition?

**Comment by Thorrik1993** [comment]
My research to fix the problem of rokups lead me here.
I use dearimgui and I rewrite the glfw part myself, to avoid some trouble that hasn't be fixed yet.
So I tried _NET_MOVERESIZE_WINDOW as @tquante suggested, but it didn't fix my problem. 
Does this atom required specific treatment. I send a _NET_MOVERESIZE_WINDOW event to move my window, but it's just place my window into a corner of my screen. Indeed, there is a move but not the right one I want.

**Comment by tquante** [comment]
I use the collowing code to change the window position with x11:

constexpr unsigned int xPosPresent = 1 << 8;
constexpr unsigned int yPosPresent = 1 << 9;
constexpr unsigned int applicationIssued = 1 << 12;
unsigned long flags = xPosPresent | yPosPresent |  applicationIssued;

XEvent event = {ClientMessage};
event.xclient.window = window;
event.xclient.format = 32; // Data is 32-bit longs
event.xclient.message_type = type;
event.xclient.data.l[0] = netSizeRemoveAtom;
event.xclient.data.l[1] = newPos.x;
event.xclient.data.l[2] = newPos.y;
event.xclient.data.l[3] = 0;
event.xclient.data.l[4] = 0;

XSendEvent(x11Display, x11RootWindow, False,
               SubstructureNotifyMask | SubstructureRedirectMask, &event);
XFlush(libraryMemory->display);

**Comment by Thorrik1993** [comment]
@jeremiahar 
Thank you very much. Your commit work well for me.
I also tried setting override_redirect=true and having the same result as you.
I understand my mistake.
When I wanted to used NET_MOVERESIZE_WINDOW, I simply replaced XMoveWindow by sendEvent. 
That's why I said in [my comment](https://github.com/glfw/glfw/issues/1817#issuecomment-1018522736): "my window was placed into a corner of my screen".
So now, my new window moves like in Mac and Windows. 
I thank you again for your response, you made my day.

**Comment by Challanger524** [comment]
Still cannot find how to move/created maximized + decorated window onto second monitor. GLFW - 🤬
