### ISSUE TITLE
Dualsense controller working in wired mode, but not in wireless mode

### ISSUE THREAD

**Issue by VagueLobster** [glfw/glfw#2726]
I have encountered an issue with GLFW where if i have my controller plugged into my pc, it can register the inputs just fine which is good of course.
But when i'm using the controller with bluetooth and only bluetooth (no cables) then i can register the controller in GLFW, but it never receives any input changes...
I'm using a GLFWGamepadState to get the buttons' and axes' values, but the values are never getting updated when using bluetooth.

The weird thing is, i know i've been able to register the values in the past, but i did update my Dualsense's firmware recently, and i don't know if that's got anything to do with my controller not getting it's buttons and axes' values updated???

**Comment by dougbinks** [comment]
A few questions:

1. Is this on Windows?
2. Are you able to see get any input using the joystick API on Bluetooth instead of the gamepad API?
3. Are you able to use the controller with other programs when on Bluetooth?
4. It may not matter but it might be worth adding the Dualsense controller model number/version in case this is specific to a given model.

**Comment by VagueLobster** [comment]
> 1. Yes, it's on Windows 11 Pro.
> 2. If i connect via Bluetooth, and i move the left analogue stick left or right i get input for a split second.
> 3. Yes i am.
> 4. Model number of my controller is: CFI-ZCT1W. I don't know how to see revision number...

**Comment by dougbinks** [comment]
Many thanks for your answers.

> If i connect via Bluetooth, and i move the left analogue stick left or right i get input for a split second.

Is that with the joystick API or the gamepad API? Is seeing input for a split second what you expect or are you moving the stick to the far left and holding it there but only seeing `0 0 0 0 -1 0 0 0` (values over time) or something similar?

It might be worth running the [joysticks.c test program](https://github.com/glfw/glfw/blob/master/tests/joysticks.c) from the release source code to see if that works for you.

**Comment by VagueLobster** [comment]
> Many thanks for your answers.

No problem 😄 

> Is that with the joystick API or the gamepad API? Is seeing input for a split second what you expect or are you moving the stick to the far left and holding it there but only seeing `0 0 0 0 -1 0 0 0` (values over time) or something similar?

That's me holding the stick to the far most left or right, and then sometimes my character just drift until i move the opposite way.
EDIT #2: the character drifts until i move the opposite way on keyboard since the controller doesn't work unless connected through cable, but if i connect it via cable and then move the opposite way then that also makes my character able to move again.
 
> It might be worth running the [joysticks.c test program](https://github.com/glfw/glfw/blob/master/tests/joysticks.c) from the release source code to see if that works for you.

I will try and do that, thanks for the suggestion 😄

**Comment by VagueLobster** [comment]
> Many thanks for your answers.
> 
> > If i connect via Bluetooth, and i move the left analogue stick left or right i get input for a split second.
> 
> Is that with the joystick API or the gamepad API? Is seeing input for a split second what you expect or are you moving the stick to the far left and holding it there but only seeing `0 0 0 0 -1 0 0 0` (values over time) or something similar?
> 
> It might be worth running the [joysticks.c test program](https://github.com/glfw/glfw/blob/master/tests/joysticks.c) from the release source code to see if that works for you.

Hi again and sorry for the late reply.
I have now tested my controller inside of the joysticks.c test app and i cannot get any signal from my controller wirelessly, however when it's connected to my pc through cable it works, so idk what could be the issue tbh :(

**Comment by VagueLobster** [comment]
Btw this is my Dualsense's GUID id according to joysticks.c

<img width="330" height="58" alt="Image" src="https://github.com/user-attachments/assets/40cbb668-f0cf-4483-8411-68eb792a86e8" />

In case it can be useful 😅

**Comment by VagueLobster** [comment]
I've also found out that it's a version 1 controller, if that can help as well

**Comment by dougbinks** [comment]
> I have now tested my controller inside of the joysticks.c test app and i cannot get any signal from my controller wirelessly, however when it's connected to my pc through cable it works, so idk what could be the issue tbh :(

If joysticks.c isn't detecting the controller at all then the issue is potentially related to DirectInput/XInput. According to what I can find online there are issues with the PS5 dualsense in Bluetooth mode.

Fixing this will likely require a significant overhaul of the win32 joystick input code.

> Btw this is my Dualsense's GUID id according to joysticks.c

I'm presuming that is when the controller is attached via a cable.

**Comment by VagueLobster** [comment]
> I'm presuming that is when the controller is attached via a cable.

No that is the GUID when it's connected via BT.
Well, just checked while having my controller connected via cable and launching joysticks.c and it's also the same GUID for cabled controller 👍

**Comment by dougbinks** [comment]
> No that is the GUID when it's connected via BT.

Ah, when you previously said that the `joysticks.c` program did not have any signal I assumed that meant it did not detect the joystick in BT mode.

Could you explain in detail exactly what happens when you run the `joysticks.c` program with the controller in BT mode vs wired mode? Please include any error output which should be in the Visual Studio Output window or the terminal if you run from a terminal.

**Comment by VagueLobster** [comment]
> Could you explain in detail exactly what happens when you run the `joysticks.c` program with the controller in BT mode vs wired mode? Please include any error output which should be in the Visual Studio Output window or the terminal if you run from a terminal.

I will try my best 😄
Okay, i just changed joysticks.c to be a Console app so i could see any errors in the first place, but there are none.

When i connect my controller via BT after joysticks.c has launched entirely, it gives me that GUID that i sent a screenshot of, and it removes it and the input window when turning off my controller in BT mode.

I have the same issue with joysticks.c as i have with my own application, meaning that if i hold the analog X to the far right or left while it's connecting, it registers that signal for a short bit, and when i release the stick it goes back to the center for the left stick X.

If i connect via BT first, and while that's connected and also connect the controller via cable, it shows 2 input windows in joysticks.c but it only ever registers connection through the cable.

And like i said previously, i don't see any errors unfortunately ☹️ 
This is the best i can explain what i've experienced so far 👍

**Comment by VagueLobster** [comment]
And this is what joysticks.c shows with the controller connected via BT

<img width="852" height="708" alt="Image" src="https://github.com/user-attachments/assets/af98eaad-53f8-4ef5-8b75-4124a82ef049" />

It says controller connected wirelessly, but the GUID is the same as when the controller is connected via cable 👍

**Comment by VagueLobster** [comment]
And this is when it's connected through both BT and cable at the same time.

<img width="829" height="687" alt="Image" src="https://github.com/user-attachments/assets/42625192-ff92-458f-a950-77638a708bf0" />

I don't know if this'll help at all, but i thought i'd show you anyways 😃

**Comment by dougbinks** [comment]
Many thanks.

With the controller connected via BT do the joystick states change in proportion to the movement of the stick? I am unsure if your earlier communications refer to the Gamepad state, Joystick state or both.

**Comment by VagueLobster** [comment]
> Many thanks.
> 
> With the controller connected via BT do the joystick states change in proportion to the movement of the stick? I am unsure if your earlier communications refer to the Gamepad state, Joystick state or both.

This is with my controller state's left analog stick moved to the right originally via BT, but it's stuck there now even after releasing the stick... i mean it's while having the stick to the far right while connecting, and for a couple of seconds it registers the state but then loses state changes:

<img width="802" height="632" alt="Image" src="https://github.com/user-attachments/assets/567f28b5-4948-408c-ac92-464943cf8a1e" />

This image is after joysticks.c has lost the state changes, so it's after i released the stick.

**Comment by VagueLobster** [comment]
But yeah, i was referring to gamepad state with my own game, and from what i can tell inside of joysticks.c it would be joystick state changes, so my understanding would mean both state changes get lost no matter what when connecting my controller via BT

EDIT: Nvm, it's only for joystick state changes, even in my own game engine, sorry about the confusion.

**Comment by VagueLobster** [comment]
This is how i check if it's connected:

```
std::unordered_map<InputKey, InputManager::InputDeviceState> Window::GetGamepadState(int joystickId)
{
	GLFWgamepadstate state;
	if (glfwGetGamepadState(joystickId, &state) == GLFW_TRUE && glfwJoystickPresent(joystickId) == GLFW_TRUE /*&& glfwJoystickIsGamepad(joystickId) == GLFW_TRUE*/)
		return m_Data.m_WindowInput.GetGamepadState(state);

	return std::unordered_map<InputKey, InputManager::InputDeviceState>{};
}

void Window::ProcessEvents()
{
	glfwPollEvents();

	for (int id = GLFW_JOYSTICK_1; id < m_GamepadRemoveIndex; id++)
	{
		auto* inputManager = Application::Get().GetInputManager();

		if (inputManager)
		{
			if (glfwJoystickPresent(id) != GLFW_TRUE)
			{
				inputManager->RemoveDevice(InputDeviceType::GAMEPAD, id);
				NZ_CORE_CRITICAL("Gamepad {} disconnected!", id);

				if (m_GamepadIndex > 0)
					m_GamepadIndex--;

				if (m_GamepadRemoveIndex > 0)
					m_GamepadRemoveIndex--;
			}
		}
	}

	for (int id = GLFW_JOYSTICK_1; id < GLFW_JOYSTICK_LAST; id++)
	{
		auto* inputManager = Application::Get().GetInputManager();

		if (inputManager)
		{
			if (glfwJoystickPresent(id) == GLFW_TRUE && m_GamepadIndex == id)
			{
				Window* window = Application::Get().GetRawWindow();

				if (window)
				{
					inputManager->RegisterDevice(InputManager::InputDevice{
						.Type = InputDeviceType::GAMEPAD,
						.Index = id,
						.StateFunc = std::bind(&Window::GetGamepadState, window, std::placeholders::_1)
					});
				}

				NZ_CORE_CRITICAL("Gamepad {} connected!", id);
				NZ_CORE_CRITICAL("glfwGetJoystickName = {}, GUID = {}!", glfwGetJoystickName(id), glfwGetJoystickGUID(id));
				NZ_CORE_CRITICAL("glfwGetGamepadName = {}!", glfwGetGamepadName(id));

				m_GamepadRemoveIndex++;
				m_GamepadIndex++;
			}
		}
	}
}
```

and this is how i update my controller's buttons and axes:
```
std::unordered_map<InputKey, InputManager::InputDeviceState> WindowsInput::GetGamepadState(const GLFWgamepadstate& state)
{
	std::unordered_map<InputKey, InputManager::InputDeviceState> gamepadState{};

	// Get the buttons
	for (int i = 0; i <= GLFW_GAMEPAD_BUTTON_LAST; i++)
	{
		int buttonState = state.buttons[i];
		float value = buttonState == GLFW_PRESS ? 1.0f : 0.0f;

		switch (i)
		{
		case GLFW_GAMEPAD_BUTTON_A:
			gamepadState[InputKey::BUTTON_A].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_B:
			gamepadState[InputKey::BUTTON_B].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_X:
			gamepadState[InputKey::BUTTON_X].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_Y:
			gamepadState[InputKey::BUTTON_Y].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_LEFT_BUMPER:
			gamepadState[InputKey::LEFT_BUMPER].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER:
			gamepadState[InputKey::RIGHT_BUMPER].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_BACK:
			gamepadState[InputKey::BACK_BUTTON].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_START:
			gamepadState[InputKey::START_BUTTON].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_GUIDE:
			gamepadState[InputKey::GUIDE_BUTTON].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_LEFT_THUMB:
			gamepadState[InputKey::LEFT_THUMB_BUTTON].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_RIGHT_THUMB:
			gamepadState[InputKey::RIGHT_THUMB_BUTTON].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_DPAD_UP:
			gamepadState[InputKey::DPAD_UP].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_DPAD_RIGHT:
			gamepadState[InputKey::DPAD_RIGHT].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_DPAD_DOWN:
			gamepadState[InputKey::DPAD_DOWN].Value = value;
			break;
		case GLFW_GAMEPAD_BUTTON_DPAD_LEFT:
			gamepadState[InputKey::DPAD_LEFT].Value = value;
			break;
		default:
			break;
		}
	}

	// Get the axes
	for (int i = 0; i <= GLFW_GAMEPAD_AXIS_LAST; i++)
	{
		float value = state.axes[i];

		switch (i)
		{
		case GLFW_GAMEPAD_AXIS_LEFT_X:
			gamepadState[InputKey::LEFT_THUMB_X].Value = value;
			break;
		case GLFW_GAMEPAD_AXIS_LEFT_Y:
			gamepadState[InputKey::LEFT_THUMB_Y].Value = -value;
			break;
		case GLFW_GAMEPAD_AXIS_RIGHT_X:
			gamepadState[InputKey::RIGHT_THUMB_X].Value = value;
			break;
		case GLFW_GAMEPAD_AXIS_RIGHT_Y:
			gamepadState[InputKey::RIGHT_THUMB_Y].Value = -value;
			break;
		case GLFW_GAMEPAD_AXIS_LEFT_TRIGGER:
			gamepadState[InputKey::LEFT_TRIGGER].Value = value;
			break;
		case GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER:
			gamepadState[InputKey::RIGHT_TRIGGER].Value = value;
			break;
		default:
			break;
		}
	}

	return gamepadState;
}
```

If this'll help solve my issues 😄

**Comment by dougbinks** [comment]
Since we're using `joysticks.c` I don't need your code, but it's important to know what it was you were measuring since the gamepad state maps joystick state in a way which could be the problem, but if `joysticks.c` is reporting odd joystick axis state then that's another thing.

I'm still not entirely clear what you are seeing in the `joysticks.c` program.

Can I ask you to try the following and report what happens at each step.

1. Connect your controller via BT. Do not touch any buttons or sticks.
2. Start `joysticks.c`. This should show the joystick connected as [Wireless Controlleras per this post](https://github.com/glfw/glfw/issues/2726#issuecomment-3092327679), let me know if so or not.
3. Move the analog X to the far right. Report what you see, e.g. *"Joystick state first slider moves to right but then moves back to center even though I was still holding the stick to the right."*
4. Move the analog X to the center, report what you see.
5. Move the analog X to the left, report what you see.

Apologies for asking a lot but it is difficult to understand what is going on when I cannot see it, and I need a simple example of the primary issue.

**Comment by dougbinks** [comment]
Oh I forgot to ask if you could also do the same but with the controller connected wired (please kill and restart the program after connecting). No rush as I will not be able to look at the code for a while.

**Comment by VagueLobster** [comment]
> Since we're using `joysticks.c` I don't need your code, but it's important to know what it was you were measuring since the gamepad state maps joystick state in a way which could be the problem, but if `joysticks.c` is reporting odd joystick axis state then that's another thing.
> 
> I'm still not entirely clear what you are seeing in the `joysticks.c` program.
> 
> Can I ask you to try the following and report what happens at each step.
> 
> 1. Connect your controller via BT. Do not touch any buttons or sticks.
> 2. Start `joysticks.c`. This should show the joystick connected as [Wireless Controlleras per this post](https://github.com/glfw/glfw/issues/2726#issuecomment-3092327679), let me know if so or not.
> 3. Move the analog X to the far right. Report what you see, e.g. _"Joystick state first slider moves to right but then moves back to center even though I was still holding the stick to the right."_
> 4. Move the analog X to the center, report what you see.
> 5. Move the analog X to the left, report what you see.
> 
> Apologies for asking a lot but it is difficult to understand what is going on when I cannot see it, and I need a simple example of the primary issue.

1 & 2 : Just did that after seeing your message here 😄 3, 4 & 5 : Tried that just now after doin steps 1 & 2, and zero input is registered 👍 

> Oh I forgot to ask if you could also do the same but with the controller connected wired (please kill and restart the program after connecting). No rush as I will not be able to look at the code for a while.

I also just repeated the steps 1 through 5 like you asked for with connected controller after i killed the application and restarted joysticks.c
And even when i connect the controller with cable before launching joysticks.c it still registers input inside of joysticks.c, so for cabled connection it works 👍 

> Apologies for asking a lot but it is difficult to understand what is going on when I cannot see it, and I need a simple example of the primary issue.

No worries at all 😄 I just hope that this can work in the end 👍

**Comment by VagueLobster** [comment]
> > Since we're using `joysticks.c` I don't need your code, but it's important to know what it was you were measuring since the gamepad state maps joystick state in a way which could be the problem, but if `joysticks.c` is reporting odd joystick axis state then that's another thing.
> > I'm still not entirely clear what you are seeing in the `joysticks.c` program.
> > Can I ask you to try the following and report what happens at each step.
> > 
> > 1. Connect your controller via BT. Do not touch any buttons or sticks.
> > 2. Start `joysticks.c`. This should show the joystick connected as [Wireless Controlleras per this post](https://github.com/glfw/glfw/issues/2726#issuecomment-3092327679), let me know if so or not.
> > 3. Move the analog X to the far right. Report what you see, e.g. _"Joystick state first slider moves to right but then moves back to center even though I was still holding the stick to the right."_
> > 4. Move the analog X to the center, report what you see.
> > 5. Move the analog X to the left, report what you see.
> > 
> > Apologies for asking a lot but it is difficult to understand what is going on when I cannot see it, and I need a simple example of the primary issue.
> 
> 1 & 2 : Just did that after seeing your message here 😄 3, 4 & 5 : Tried that just now after doin steps 1 & 2, and zero input is registered 👍
> 
> > Oh I forgot to ask if you could also do the same but with the controller connected wired (please kill and restart the program after connecting). No rush as I will not be able to look at the code for a while.
> 
> I also just repeated the steps 1 through 5 like you asked for with connected controller after i killed the application and restarted joysticks.c And even when i connect the controller with cable before launching joysticks.c it still registers input inside of joysticks.c, so for cabled connection it works 👍

> Apologies for asking a lot but it is difficult to understand what is going on when I cannot see it, and I need a simple example of the primary issue.

No worries at all 😄 I just hope that this can work in the end 👍

**Comment by VagueLobster** [comment]
Hi Doug,
I have very recently switched to use Wayland with KDE Plasma as DE, and i have also tried to use my PS5 Dualsense controller with my applications, and it works flawlessly when using wireless mode on Wayland, so now i'm 99.9% sure that it's gotta be a glfw bug with it's Windows input handling...
Because like i said previously i know i can use my controller in wireless mode in Windows with the games that support it 👍
